name: 'Check Chef Cookbook Metadata'
description: 'A GitHub Action to check cookbook metadata is correct.'
branding:
  icon: user-check
  color: green
author: 'damacus'
inputs:
  github-token:
    description: 'Github token'
    required: true
  maintainer_email:
    description: 'Maintainer email'
    required: false
    default: help@sous-chefs.org
  maintainer:
    description: 'Desired name of the maintainer'
    required: false
    default: 'Sous Chefs'
  license:
    description: 'A SPDX licence'
    required: false
    default: 'Apache-2.0'
  file_path:
    description: 'Path to the metadata.rb file'
    required: false
    default: 'metadata.rb'
  report_checks:
    description: 'Report the result as a check'
    required: false
    default: 'true'
  comment_on_pr:
    description: 'Comment on the PR with the result'
    required: false
    default: 'true'
runs:
  using: 'node20'
  main: 'dist/index.js'
