name: "Check Chef Cookbook Metadata"
description: "A GitHub Action to check cookbook metadata is correct."
branding:
  icon: alert-triangle
  color: green
author: "damacus"
inputs:
  token:
    description: "Github token"
    required: true
  maintainer_email:
    description: "Maintainer email"
    required: false
    default: help@sous-chefs.org
  maintainer:
    description: "Desired name of the maintainer"
    required: false
    default: 'Sous Chefs'
  license:
    description: "A SPDX licence"
    required: false
    default: 'Apache-2.0'

runs:
  using: "node16"
  main: "dist/index.js"
