name: 'Check Chef Cookbook Metadata'
description: 'A GitHub Action to check cookbook metadata is correct.'
branding:
  icon: user-check
  color: green
author: 'damacus'
inputs:
  github-token:
    description: 'Github token'
    required: true
  maintainer_email:
    description: 'Maintainer email'
    required: false
    default: help@sous-chefs.org
  maintainer:
    description: 'Desired name of the maintainer'
    required: false
    default: 'Sous Chefs'
  license:
    description: 'A SPDX licence'
    required: false
    default: 'Apache-2.0'
  file_path:
    description: 'Path to the metadata.rb file'
    required: false
    default: 'metadata.rb'
  report_checks:
    description: 'Report the result as a check'
    required: false
    default: 'true'
  comment_on_pr:
    description: 'Comment on the PR with the result'
    required: false
    default: 'true'
  mandatory_fields:
    description: 'Comma-separated list of mandatory fields'
    required: false
    default: 'version,chef_version,supports'
  parallel_limit:
    description: 'Maximum number of metadata files to validate in parallel'
    required: false
    default: '10'
  url_timeout:
    description: 'Timeout in milliseconds for URL accessibility checks'
    required: false
    default: '5000'
  url_retries:
    description: 'Number of retries for URL accessibility checks on transient failures'
    required: false
    default: '2'
outputs:
  cookbooks:
    description: 'A JSON string representing an array of validated cookbook objects.'
  cookbook-name:
    description: 'The name of the cookbook (if exactly one cookbook was found).'
  cookbook-version:
    description: 'The version of the cookbook (if exactly one cookbook was found).'
runs:
  using: 'node20'
  main: 'dist/index.js'
