---
name: Check action

'on':
  push:
    branches: [main]
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']
  workflow_dispatch:

jobs:
  test-failure:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          maintainer_email: help@sous-chefs.org
          file_path: test/fixtures/metadata.incorrect.rb

  test-success:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          maintainer_email: help@sous-chefs.org
          file_path: test/fixtures/metadata-action.rb
