---
name: Check action

'on':
  push:
    branches: [main]
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']
  workflow_dispatch:

jobs:
  test-failure:
    runs-on: ubuntu-latest
    permissions:
      checks: write # required for the status check
      pull-requests: write # required for the PR comment ### AND SOMETHING ELSE TODO: find what the hell this does
      statuses: write # required for the status check
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: ./
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file_path: test/fixtures/metadata.incorrect.rb
          report_checks: true
          comment_on_pr: true

  test-success:
    needs: test-failure
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file_path: test/fixtures/metadata-action.rb
