---
name: release-please

"on":
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v6

      - name: Update major/minor tags
        if: ${{ steps.release.outputs.release_created }}
        env:
          MAJOR: ${{ steps.release.outputs.major }}
          MINOR: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -f v$MAJOR
          git tag -f v$MINOR
          git push -f origin v$MAJOR
          git push -f origin v$MINOR
